language: java
sudo: false

jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
install: true #跳过安装


env:
  global:
    - branch_name: maven-dep-mechanism
    - branch_version: 2.0
    - repo_url: github.com/zhaoyunxing92/maven-learn.git

#before_install:
#  - echo "install maven 3.6.1"
#  - wget https://mirrors.tuna.tsinghua.edu.cn/apache/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.zip
#   && unzip -qq apache-maven-3.6.1-bin.zip
#   && export M2_HOME=$PWD/apache-maven-3.2.5
#   && export PATH=$M2_HOME/bin:$PATH
#   && mvn -version

# 配置邮箱通知
notifications:
  email:
    on_failure: always # 失败通知
    on_success: never # 成功不通知:never
#    recipients:  #列表没有配置成功
#      - zhaoyunxing@ccclubs.com
#      - 2385585770@qq.com


# 只在master分支工作
branches:
  only:
    - maven-dep-mechanism

before_script:
  - echo 'maven install user-api 1.0、2.0、3.0'
  - mvn install -Drevision=1.0 -pl server/user-server/user-api -am && mvn install -Drevision=2.0 -pl server/user-server/user-api -am && mvn install -Drevision=3.0 -pl server/user-server/user-api -am

script:
  - travis_wait 15 mvn compile -Drevision=${branch_version} -Dmaven.test.skip=false -Dcheckstyle.skip=false

# 成功后创建分支
after_success:
  - echo mvn compile success begin git make branch

# 失败后撤回代码
after_failure:
  - echo mvn comile fail begin git rooback