language: java
sudo: false

jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
install: true

# 配置邮箱通知
notifications:
  email:
    on_failure: always # 失败通知
    on_success: always # 成功不通知:never
#    recipients:  #列表没有配置成功
#      - zhaoyunxing@ccclubs.com
#      - 2385585770@qq.com

before_deploy:
  - echo maven runing

# 只在master分支工作
branches:
  only:
    - master

script:
  - travis_wait 30 mvn clean compile -Dmaven.test.skip=false -Dcheckstyle.skip=false


deploy:
  provider: releases
  skip_cleanup: true
  github_token: ${github_token}
  on:
    branch: master

# 成功后创建分支
after_success:
  - echo mvn compile success begin git make branch
  - git log
  - git config user.name "${name}"
  - git config user.email "${email}"
  - git config user.name
  - git remote -v
  #- bash <(curl -s https://codecov.io/bash) # 编译通过后启用codecov

# 失败后撤回代码
