language: java
sudo: false

jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
#install: true #跳过安装

env:
  global:
    - branch_name: maven-2.x
    - branch_version: 2.0
    - repo_url: github.com/zhaoyunxing92/maven-learn.git

#before_install:
#  - echo "install maven 3.6.1"
#  - wget https://mirrors.tuna.tsinghua.edu.cn/apache/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.zip
#   && unzip -qq apache-maven-3.6.1-bin.zip
#   && export M2_HOME=$PWD/apache-maven-3.2.5
#   && export PATH=$M2_HOME/bin:$PATH
#   && mvn -version

# 配置邮箱通知
notifications:
  email:
    on_failure: always # 失败通知
    on_success: always # 成功不通知:never
#    recipients:  #列表没有配置成功
#      - zhaoyunxing@ccclubs.com
#      - 2385585770@qq.com

# 只在master分支工作
branches:
  only:
    - master

script:
  - travis_wait 15 mvn install -pl maven-plgu-case -am
   && mvn clean compile -Dmaven.test.skip=false -Dcheckstyle.skip=false

# 成功后创建分支
after_success:
  - echo mvn compile success begin git make branch
  - git chechout -b ${branch_name}
  - git config user.name "${name}"
  - git config user.email "${email}"
  - mvn versions:set -DnewVersion=${branch_version}
  - mvn versions:commit
  - git commit -am '[up]修改版本为${branch_name}'
  - git push -f --quiet "https://${github_token}@${repo_url}" ${branch_name}
  #- bash <(curl -s https://codecov.io/bash) # 编译通过后启用codecov

# 失败后撤回代码
after_failure:
  - echo mvn comile fail begin git rooback
  - git config user.name "${name}"
  - git config user.email "${email}"
  - git reset --hard ^
  - git push -f --quiet "https://${github_token}@${repo_url}" ${branch_name}:${branch_name}