language: java
sudo: false

jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
install: true

# 配置邮箱通知
notifications:
  email:
    on_failure: always # 失败通知
    on_success: never # 成功不通知
#    recipients:  列表没有配置成功
#      - zhaoyunxing@ccclubs.com
#      - 2385585770@qq.com

#deploy:

#  provider: script
#  script: travis_wait 30 mvn clean package -DskipTests=false -Dcheckstyle.skip=false
#  on:
#    branch: master
before_deploy:
  - echo maven runing

script:
  - travis_wait 30 mvn clean package -Dmaven.test.skip=true -Dcheckstyle.skip=true

#after_success:
#  - echo mvn package success
#  - bash <(curl -s https://codecov.io/bash) # 编译通过后启用codecov
